# Generated by Django 5.1.6 on 2025-05-29 13:38

import hospital.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=30, unique=True)),
                ('details', models.TextField(blank=True, help_text='Information related to this department.', null=True)),
                ('profile', models.ImageField(blank=True, default='default/medical-equipment-4099429_1920.jpg', help_text="Department's profile picture", upload_to=hospital.utils.generate_document_filepath, verbose_name='Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the treatment was created', verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT')], default='Day', max_length=40)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salary in Ksh', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specality name', max_length=50, unique=True)),
                ('details', models.TextField(blank=True, help_text='Information related to this speciality.', null=True)),
                ('appointment_charges', models.DecimalField(decimal_places=2, default=0, help_text='Appointment charges in Ksh', max_digits=8)),
                ('treatment_charges', models.DecimalField(decimal_places=2, default=0, help_text='Treatment charges in Ksh', max_digits=8)),
                ('appointments_limit', models.IntegerField(default=20, help_text='Daily appointments limit')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], help_text='Weekday name', max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the treatment was created', verbose_name='Created At')),
            ],
        ),
    ]
