# Generated by Django 5.1.6 on 2025-05-29 13:38

import hospital.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(help_text='The date and time of the appointment')),
                ('reason', models.TextField(help_text='The reason for the appointment')),
                ('status', models.CharField(choices=[('Scheduled', 'SCHEDULED'), ('Completed', 'COMPLETED'), ('Cancelled', 'CANCELLED')], default='Scheduled', help_text='Select appointment status', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the appointment was last updated', verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the appointment was created', verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the medicine', max_length=255, unique=True, verbose_name='Medicine Name')),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name for the medicine', max_length=20, null=True, unique=True, verbose_name='Abbreviated name')),
                ('category', models.CharField(choices=[('Antibiotics', 'ANTIBIOTICS'), ('Pain Relief', 'PAIN_RELIEF'), ('First Aid', 'FIRST_AID'), ('Vitamins', 'VITAMINS'), ('Supplements', 'SUPPLEMENTS'), ('Cough Syrup', 'COUGH_SYRUP'), ('Other', 'OTHER')], default='Other', help_text='Select the category of the medicine', max_length=50, verbose_name='Category')),
                ('description', models.TextField(help_text='Provide a detailed description of the medicine', verbose_name='Description')),
                ('expiry_date', models.DateField(help_text='Expiration date')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the medicine in Kenyan Shillings', max_digits=10, verbose_name='Price in Ksh')),
                ('stock', models.PositiveIntegerField(help_text='Enter the current stock level of the medicine', verbose_name='Stock Level')),
                ('picture', models.ImageField(blank=True, default='default/ai-generated-medicine.jpg', help_text='Photo of the medicine', upload_to=hospital.utils.generate_document_filepath, verbose_name='Photo of the medicine')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the medicine was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the medicine was last updated', verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the treatment was created', verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('Outpatient', 'OUTPATIENT'), ('Inpatient', 'INPATIENT')], default='Outpatient', help_text='Select whether the patient is an outpatient or inpatient', max_length=20)),
                ('diagnosis', models.CharField(help_text='The diagnosis of the patient', max_length=255)),
                ('details', models.TextField(help_text='The treatment given to the patient')),
                ('treatment_status', models.CharField(choices=[('Inprogress', 'INPROGRESS'), ('Healed', 'HEALED'), ('Referred', 'REFERRED')], default='Inprogress', help_text='Treatment status', max_length=20)),
                ('bill_settled', models.DecimalField(decimal_places=2, default=0, help_text='Amount of bill paid so far', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the treatment was last updated', verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the treatment was created', verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Medicine amount')),
                ('prescription', models.TextField(help_text='Medicine prescription')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
