# Generated by Django 5.1.6 on 2025-05-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external', '0001_initial'),
        ('hospital', '0001_initial'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(help_text='The doctor for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='staffing.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, help_text='Appointment service feedback', related_name='appointments', to='external.servicefeedback'),
        ),
    ]
